using System.ComponentModel.DataAnnotations;

namespace UserManagementAPI.Models
{
    /// <summary>
    /// Represents a user entity stored in the database.
    /// </summary>
    public class User
    {
        /// <summary>The unique identifier for the user. Auto-generated by the database.</summary>
        public int Id { get; set; }

        /// <summary>The user's full name.</summary>
        [Required]
        [MaxLength(100)]
        public string Name { get; set; }

        /// <summary>The user's email address. Must be unique.</summary>
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        /// <summary>The user's date of birth.</summary>
        [Required]
        public DateTime DateOfBirth { get; set; }

        /// <summary>The UTC timestamp when the user was created.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>The UTC timestamp when the user was last updated.</summary>
        public DateTime UpdatedAt { get; set; }

    }
}
